set -g default-terminal "screen-256color"
## BAR
set -g status-bg colour32
set -g status-fg colour231
set -g window-status-style bg=colour3,fg=colour124
set -g window-status-current-style bg=colour124,fg=colour3
#
## Change prefix key to C-a, easier to type, same to "screen"
unbind C-b
set -g prefix M-a
bind-key M-a send-prefix

set -sg escape-time 0

##MOUSE!
# remember to use shift for default mouse beaviour on select+copy and paste
set -g mouse on
set-option -s set-clipboard off


## Creating splits
bind n split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

## Moving between splits
# smart pane switching with awareness of vim splits, requires christoomey/vim-tmux-navigator on .vimrc
bind h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
#bind \ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

## Resizing splits
bind -n M-h resize-pane -L 2
bind -n M-l resize-pane -R 2
bind -n M-k resize-pane -U 2
bind -n M-j resize-pane -D 2

## Creating window, moving between windows
set -g base-index 1       # Start numbering windows at 1, not 0.
set -g pane-base-index 1  # Start numbering panes at 1, not 0.
bind -n C-t new-window -c '#{pane_current_path}'
bind -n C-h previous-window
bind -n C-l next-window
#bind -n C-S-Left swap-window -t -1\; select-window -t -1
#bind -n C-S-Right swap-window -t +1\; select-window -t +1
#bind -n C-S-h swap-window -t -1
#bind -n C-S-l swap-window -t +1
#bind-key -n C-S-h move-window -t -1
#bind-key -n C-S-l move-window -t +1
bind -n C-S-h swap-window -t -1\; select-window -t -1
bind -n C-S-l swap-window -t +1\; select-window -t +1

# Macos copypaste, needs brew install reattach-to-user-namespace
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

set-option -g history-limit 300000
