appearance:
  mode: System
  theme: blue
application:
  auto_save: true
  language: en
  notifications: true
backup:
  compression: true
  default_type: full
  encryption: false
  media:
  - path: /media/aaf/TESTIESS
    tiers:
    - tier1
  tiers:
    tier1:
      description: Essential system files and critical user data
      exclude: []
      include:
      - /home/aaf/.ssh
      - /home/aaf/Private
      name: Critical Data
    tier2:
      description: Important documents and frequently used files
      exclude: []
      include: []
      name: Important Data
    tier3:
      description: Large files and archives, backed up less frequently
      exclude: []
      include: []
      name: Archive Data
restore:
  create_backup_before_restore: true
  verification: true
