set nocompatible
set t_Co=256
" set termguicolors
" set background=dark  
" colorscheme kuroi

"-""colorscheme atom-dark-256

"-"  install vim-gitgutter
" mkdir -p ~/.vim/pack/airblade/start
" cd ~/.vim/pack/airblade/start
" git clone https://github.com/airblade/vim-gitgutter.git
" vim -u NONE -c "helptags vim-gitgutter/doc" -c q
""

filetype off
"-" 
call plug#begin('~/.vim/plugged')
" Make sure you use single quotes

Plug 'BurntSushi/ripgrep'
Plug 'Shougo/neocomplete.vim'
Plug 'flazz/vim-colorschemes'
Plug 'jiangmiao/auto-pairs'
Plug 'jreybert/vimagit'
Plug 'junegunn/fzf'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install' }
Plug 'prettier/vim-prettier'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vimwiki/vimwiki'
Plug 'pedrohdz/vim-yaml-folds'

call plug#end()"-" 
"-"  " To install:
"-"  " :PlugInstall
"-"  " vim +PluginInstall +qall

filetype plugin indent on " required
"-"execute pathogen#infect() 
"-""-" ARDUINO#
"-"let g:vim_arduino_library_path = "/home/aaf/arduino-1.8.10"
"-"let g:vim_arduino_serial_port = "/dev/ttyUSB0"

let g:neocomplete#enable_at_startup = 1
"-" 
"-" " ####  FUNCTIONS
"-" 
"-" " Thanks https://github.com/tpope/vim-unimpaired but I just needed this
function! s:setup_paste() abort
  let s:paste = &paste
  let s:mouse = &mouse
  set paste
  set mouse=
  augroup unimpaired_paste
    autocmd!
    autocmd InsertLeave *
          \ if exists('s:paste') |
          \   let &paste = s:paste |
          \   let &mouse = s:mouse |
          \   unlet s:paste |
          \   unlet s:mouse |
          \ endif |
          \ autocmd! unimpaired_paste
  augroup END
endfunction
"-" 
"-" " ####  IDE
"-" 
syntax on
"-" 
set autoindent
"-" 
"-" " show line numbers
"-" ""set number
"-" 
"-" " show matching brackets
set showmatch
"-" 
"-" " ####  ENCODING
"-" 
set encoding=utf-8
"-" 
"-" " make backspace work as expected
set backspace=2
"-" 
"-" " set tab indenting
set tabstop=2
set shiftwidth=2
"-" " make spaces feel like tabs
set softtabstop=2
"-" " expand tabs to spaces
set expandtab
"-" 
"-" 
"-" 
"-" " ####  SEARCH
"-" 
"-" " disregard case during search
set ignorecase
"-" 
"-" " highlight search results
set hlsearch
"-" 
"-" " wrap search
set wrapscan
"-" 
"-" " highlight line containing caret
set cursorline
set cursorcolumn
"-" 
"-" 
"-" " #### VIMWIKI
"-" 
let g:vimwiki_list = [{'path': '$HOME/Software/Dev/wiki'}]
"-" 
"-" " ####  MAP KEYS
"-" 
"-" " unimpaired mapping for set paste
nnoremap <silent> yo  :call <SID>setup_paste()<CR>o
nnoremap <silent> yO :call <SID>setup_paste()<CR>O
nnoremap <silent> yi  :call <SID>setup_paste()<CR>i
nnoremap <silent> yI :call <SID>setup_paste()<CR>I
nnoremap <silent> ya  :call <SID>setup_paste()<CR>a
nnoremap <silent> yA :call <SID>setup_paste()<CR>A
"-" 
"-" 
"-" " No arrows
nnoremap <Left> :echo "No left for you!"<CR>
vnoremap <Left> :<C-u>echo "No left for you!"<CR>
nnoremap <Right> :echo "No Right for you!"<CR>
vnoremap <Right> :<C-u>echo "No Right for you!"<CR>
nnoremap <Up> :echo "No Up for you!"<CR>
vnoremap <Up> :<C-u>echo "No Up for you!"<CR>
nnoremap <Down> :echo "No Down for you!"<CR>
vnoremap <Down> :<C-u>echo "No Down for you!"<CR>

"-" " Exit insert mode on the correct character (not confusing i and a)
"-" "http://stackoverflow.com/questions/2295410/prevent-cursor-from-moving-back-one-character-on-insert-mode-exit
:inoremap <silent> <Esc> <Esc>`^
"-" 
"-" 
"-" " Powerline configs 
let g:airline_powerline_fonts = 1
set laststatus=2
set ttimeoutlen=50

" .............................................................................
" iamcco/markdown-preview.nvim
" .............................................................................

let g:mkdp_auto_close=0
let g:mkdp_refresh_slow=1
let g:mkdp_markdown_css='/home/aaf/.local/lib/github-markdown.css'
