#!/bin/sh

# Keyboard
setxkbmap -option compose:rctrl
xmodmap /home/aaf/sysangel/files/Xmodmap_mac_ctrl
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# Touchpad
if egrep -iq 'touchpad' /proc/bus/input/devices; then
  synclient VertEdgeScroll=1 TapButton1=1 HorizScrollDelta=-150 VertScrollDelta=-150 &
fi

#seahorse &
