INSTALL:
  - fabric
  - jq
  - openssh-client
  - pdftk
  - python
  - python-pip
  - vim
  - vim-gtk
  - zeal
  - zim

SPECIAL_INSTALL:
  - boto:
    - command:
      - if [ $(pip list | grep boto | wc -l) -ne 1 ]; then sudo pip install boto; fi
    - type:
      - pip
  - gyazo:
    - command:
      - curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
  - PyYAML:
    - command:
      - if [ $(pip list | grep PyYAML | wc -l) -ne 1 ]; then sudo pip install pyyaml; fi
    - type:
      - pip

UNINSTALL:
  - fslint:
    - type:
      - apt
  - openssh-server:
